-- dashboards-mv.sql — extends the otel bentoclick de-tok MV with a
-- `system_anon -> system` rewrite (alongside the existing
-- `claude_otel_anon -> claude_otel`), so a saved system-health spec
-- (authored by the LLM against system_anon, with tokens) renders for the
-- human against REAL system, with identifiers de-tok'd to real names.
--
-- Generated by capturing the live SHOW CREATE and wrapping the panels
-- de-tok expression in one more replaceRegexpAll. Apply with:
--   cl otel --query 'DROP TABLE bentoclick.dashboards_mv'
--   cl otel --multiquery < dashboards-mv.sql
-- (single-node otel install; no ON CLUSTER needed). Re-derive after any
-- upstream change to the otel MV.

CREATE MATERIALIZED VIEW bentoclick.dashboards_mv TO bentoclick.dashboards
(
    `slug` String,
    `title` String,
    `subtitle` String,
    `concurrent` Bool,
    `spec_version` UInt8,
    `params` Array(JSON),
    `panels` Array(JSON),
    `meta` JSON,
    `tags` Array(String),
    `owner` String,
    `updated_at` DateTime
)
DEFINER = bentoclick_definer SQL SECURITY DEFINER
AS SELECT
    slug,
    title,
    subtitle,
    concurrent,
    spec_version,
    JSONExtract(params, 'Array(JSON)') AS params,
    JSONExtract(replaceRegexpAll(replaceRegexpAll(arrayFold((acc, tok) -> replaceRegexpAll(acc, concat('\\b', tok, '\\b'), dictGetOrDefault('altinity.token_to_real', 'original', tuple(tok), tok)), arrayDistinct(extractAll(replaceRegexpAll(replaceRegexpAll(panels, '(?is)<script\\b[^>]*>.*?<\\\\?/script[^>]*>|<iframe\\b[^>]*>.*?<\\\\?/iframe[^>]*>|<object\\b[^>]*>.*?<\\\\?/object[^>]*>|<svg\\b[^>]*>.*?<\\\\?/svg[^>]*>|<math\\b[^>]*>.*?<\\\\?/math[^>]*>|<style\\b[^>]*>.*?<\\\\?/style[^>]*>|<form\\b[^>]*>.*?<\\\\?/form[^>]*>|<(?:script|iframe|object|svg|math|style|form|embed|link|base|meta)\\b[^>]*\\\\?/?>|\\bon[a-z]+\\s*=\\s*(?:\\\\?"[^"]*\\\\?"|\'[^\']*\'|[^\\s>"\']+)', ''), '(?i)javascript:', ''), '(?:db|tbl|col|user|role|dict|cluster|disk|host|sql|field|enum)_[0-9a-f]{8,16}')), replaceRegexpAll(replaceRegexpAll(panels, '(?is)<script\\b[^>]*>.*?<\\\\?/script[^>]*>|<iframe\\b[^>]*>.*?<\\\\?/iframe[^>]*>|<object\\b[^>]*>.*?<\\\\?/object[^>]*>|<svg\\b[^>]*>.*?<\\\\?/svg[^>]*>|<math\\b[^>]*>.*?<\\\\?/math[^>]*>|<style\\b[^>]*>.*?<\\\\?/style[^>]*>|<form\\b[^>]*>.*?<\\\\?/form[^>]*>|<(?:script|iframe|object|svg|math|style|form|embed|link|base|meta)\\b[^>]*\\\\?/?>|\\bon[a-z]+\\s*=\\s*(?:\\\\?"[^"]*\\\\?"|\'[^\']*\'|[^\\s>"\']+)', ''), '(?i)javascript:', '')), '\\bclaude_otel_anon\\b', 'claude_otel'), '\\bsystem_anon\\b', 'system'), 'Array(JSON)') AS panels,
    CAST(meta, 'JSON') AS meta,
    JSONExtract(tags, 'Array(String)') AS tags,
    currentUser() AS owner,
    now() AS updated_at
FROM bentoclick.dashboards_raw
